<a href="https://colab.research.google.com/github/yuziny/ML_miniproject/blob/main/Mobile_KNN_RandomSearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RandomSearch KNN알고리즘 모델 튜닝

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

In [2]:
path = 'https://raw.githubusercontent.com/jangrae/csv/master/mobile.csv'
data = pd.read_csv(path)

In [3]:
data.head()

id  COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0   1        0   31953        0         6  313378            161   
1   2        1   36147        0        13  800586            244   
2   3        1   27273      230         0  305049            201   
3   4        0  120070       38        33  788235            780   
4   5        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION REPORTED_SATISFACTION  \
0                            0                      4                 unsat   
1                            0                      6                 unsat   
2                           16                     15                 unsat   
3                            3                      2                 unsat   
4                           21                      1            very_unsat   

  REPORTED_USAGE_LEVEL CONSIDERING_CHANGE_OF_PLAN  CHURN  
0               little                         no      0  
1               little                considering      0  
2          very_little                    perhaps      0  
3            very_high                considering      1  
4               little              never_thought      0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   id                           20000 non-null  int64 
 1   COLLEGE                      20000 non-null  int64 
 2   INCOME                       20000 non-null  int64 
 3   OVERAGE                      20000 non-null  int64 
 4   LEFTOVER                     20000 non-null  int64 
 5   HOUSE                        20000 non-null  int64 
 6   HANDSET_PRICE                20000 non-null  int64 
 7   OVER_15MINS_CALLS_PER_MONTH  20000 non-null  int64 
 8   AVERAGE_CALL_DURATION        20000 non-null  int64 
 9   REPORTED_SATISFACTION        20000 non-null  object
 10  REPORTED_USAGE_LEVEL         20000 non-null  object
 11  CONSIDERING_CHANGE_OF_PLAN   20000 non-null  object
 12  CHURN                        20000 non-null  int64 
dtypes: int64(10), object(3)
memory 

In [5]:
data.describe()

id       COLLEGE         INCOME       OVERAGE      LEFTOVER  \
count  20000.000000  20000.000000   20000.000000  20000.000000  20000.000000   
mean   10000.500000      0.502400   80281.447750     85.979550     23.898650   
std     5773.647028      0.500007   41680.586319     85.992324     26.816645   
min        1.000000      0.000000   20007.000000     -2.000000      0.000000   
25%     5000.750000      0.000000   42217.000000      0.000000      0.000000   
50%    10000.500000      1.000000   75366.500000     59.000000     14.000000   
75%    15000.250000      1.000000  115881.750000    179.000000     41.000000   
max    20000.000000      1.000000  159983.000000    335.000000     89.000000   

               HOUSE  HANDSET_PRICE  OVER_15MINS_CALLS_PER_MONTH  \
count   20000.000000   20000.000000                 20000.000000   
mean   493155.264250     389.615100                     8.000700   
std    252407.884692     213.820682                     8.925418   
min    150002.000000     130.000000                     0.000000   
25%    263714.250000     219.000000                     1.000000   
50%    452259.500000     326.000000                     4.000000   
75%    702378.000000     533.250000                    15.000000   
max    999996.000000     899.000000                    29.000000   

       AVERAGE_CALL_DURATION         CHURN  
count           20000.000000  20000.000000  
mean                6.002250      0.492600  
std                 4.402558      0.499958  
min                 1.000000      0.000000  
25%                 2.000000      0.000000  
50%                 5.000000      0.000000  
75%                10.000000      1.000000  
max                15.000000      1.000000

# 전처리

변수 제거

In [6]:
drop_cols = ['id']
data.drop(drop_cols, axis=1, inplace=True)
data.head()

COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0        0   31953        0         6  313378            161   
1        1   36147        0        13  800586            244   
2        1   27273      230         0  305049            201   
3        0  120070       38        33  788235            780   
4        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION REPORTED_SATISFACTION  \
0                            0                      4                 unsat   
1                            0                      6                 unsat   
2                           16                     15                 unsat   
3                            3                      2                 unsat   
4                           21                      1            very_unsat   

  REPORTED_USAGE_LEVEL CONSIDERING_CHANGE_OF_PLAN  CHURN  
0               little                         no      0  
1               little                considering      0  
2          very_little                    perhaps      0  
3            very_high                considering      1  
4               little              never_thought      0

x, y 분리

In [7]:
target = 'CHURN'

x = data.drop(target, axis=1)
y = data.loc[:, target]

가변수화

In [8]:
dumm_cols = ['REPORTED_SATISFACTION', 'REPORTED_USAGE_LEVEL', 'CONSIDERING_CHANGE_OF_PLAN']

x = pd.get_dummies(x, columns=dumm_cols, drop_first=True)
x.head()

COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0        0   31953        0         6  313378            161   
1        1   36147        0        13  800586            244   
2        1   27273      230         0  305049            201   
3        0  120070       38        33  788235            780   
4        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION  \
0                            0                      4   
1                            0                      6   
2                           16                     15   
3                            3                      2   
4                           21                      1   

   REPORTED_SATISFACTION_sat  REPORTED_SATISFACTION_unsat  \
0                          0                            1   
1                          0                            1   
2                          0                            1   
3                          0                            1   
4                          0                            0   

   REPORTED_SATISFACTION_very_sat  REPORTED_SATISFACTION_very_unsat  \
0                               0                                 0   
1                               0                                 0   
2                               0                                 0   
3                               0                                 0   
4                               0                                 1   

   REPORTED_USAGE_LEVEL_high  REPORTED_USAGE_LEVEL_little  \
0                          0                            1   
1                          0                            1   
2                          0                            0   
3                          0                            0   
4                          0                            1   

   REPORTED_USAGE_LEVEL_very_high  REPORTED_USAGE_LEVEL_very_little  \
0                               0                                 0   
1                               0                                 0   
2                               0                                 1   
3                               1                                 0   
4                               0                                 0   

   CONSIDERING_CHANGE_OF_PLAN_considering  \
0                                       0   
1                                       1   
2                                       0   
3                                       1   
4                                       0   

   CONSIDERING_CHANGE_OF_PLAN_never_thought  CONSIDERING_CHANGE_OF_PLAN_no  \
0                                         0                              1   
1                                         0                              0   
2                                         0                              0   
3                                         0                              0   
4                                         1                              0   

   CONSIDERING_CHANGE_OF_PLAN_perhaps  
0                                   0  
1                                   0  
2                                   1  
3                                   0  
4                                   0

학습용, 평가용 데이터 분리

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

정규화

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_test_s = scaler.transform(x_test)

# 성능 예측 (K분할교차검증)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

model = KNeighborsClassifier()

cv_score = cross_val_score(model, x_train_s, y_train, cv=5, scoring='accuracy')

print(cv_score)
print('평균:', cv_score.mean())
print('표준편차:', cv_score.std())

[0.58571429 0.60035714 0.57785714 0.60321429 0.59785714]
평균: 0.5930000000000001
표준편차: 0.009637829377097347


# 모델 튜닝

RandomSearch

In [12]:
from sklearn.model_selection import RandomizedSearchCV

# 파라미터 선언
param = {'n_neighbors': range(3,21)}

# 기본 모델 선언
model_knn = KNeighborsClassifier()

# Random Search 선언
model = RandomizedSearchCV(model_knn,
                           param,
                           cv=5,
                           n_iter=20,
                           scoring='accuracy'
                           )

In [13]:
model.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=20,
                   param_distributions={'n_neighbors': range(3, 21)},
                   scoring='accuracy')

In [14]:
model.cv_results_['mean_test_score']

array([0.574     , 0.5615    , 0.58542857, 0.57257143, 0.59035714,
       0.57821429, 0.59357143, 0.58307143, 0.5965    , 0.58435714,
       0.60171429, 0.58978571, 0.6035    , 0.59442857, 0.60342857,
       0.593     , 0.60621429, 0.594     ])

In [16]:
model.best_params_

{'n_neighbors': 19}

In [17]:
model.best_score_

0.6062142857142857

# 성능평가

In [18]:
y_pred = model.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1481 1584]
 [ 864 2071]]
              precision    recall  f1-score   support

           0       0.63      0.48      0.55      3065
           1       0.57      0.71      0.63      2935

    accuracy                           0.59      6000
   macro avg       0.60      0.59      0.59      6000
weighted avg       0.60      0.59      0.59      6000

